spring:
  application:
    name: spring-data

  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  main:
    allow-bean-definition-overriding: true

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api

